// ─── Exercise.model.js ───────────────────────────────────────────────────────
// An Exercise is a single question linked to a Concept.
// Types:
//   - mcq        → multiple choice, one correct answer from options[]
//   - step-based → solve in steps, each step has an expectedAnswer
//   - fill-blank → fill in blank(s) in a sentence
//   - open       → free-text answer (AI grades this — see TODO below)
//
// AI-GENERATED EXERCISES:
//   When isAiGenerated = true, the question was created by questionGen.service.js.
//   The generationSeed stores the prompt seed so we can re-create the same question.

import mongoose from "mongoose";

const stepSchema = new mongoose.Schema({
    stepNumber: { type: Number, required: true },
    instruction: { type: String, required: true },
    expectedAnswer: { type: String, required: true },
    // Hint shown to student if they get this step wrong
    hint: { type: String },
});

const exerciseSchema = new mongoose.Schema(
    {
        conceptId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Concept",
            required: true,
            index: true,
        },
        type: {
            type: String,
            enum: ["mcq", "step-based", "fill-blank", "open"],
            required: true,
            index: true,
        },
        question: { type: String, required: true },
        // Only for MCQ: list of answer choices
        options: [{ type: String }],
        // Only for step-based: ordered list of steps
        steps: [stepSchema],
        // The complete correct answer / worked solution
        solution: { type: String },
        difficulty: {
            type: Number,
            min: 1,
            max: 5,
            default: 3,
            index: true,
        },
        // Was this question auto-generated by AI or written manually by a teacher?
        isAiGenerated: { type: Boolean, default: false },
        // The seed string used to call AI, so we can reproduce the same question later
        // TO ADD AI: Pass this seed to questionGen.service.js when regenerating
        generationSeed: { type: String },
    },
    { timestamps: true }
);

const Exercise = mongoose.model("Exercise", exerciseSchema);
export default Exercise;
