// ─── notes.service.js ────────────────────────────────────────────────────────
// Smart notes: converts student's highlighted text into AI summaries and flashcards.
//
// ⚠️  CURRENTLY USING DUMMY SUMMARIES — REAL AI NOT CONNECTED YET
//
// HOW TO CONNECT REAL AI (GPT-4o Summarisation):
// ────────────────────────────────────────────────
// Step 1: In generateSummary(), replace the DUMMY block with:
//
//   import { ChatOpenAI } from "@langchain/openai";
//   const llm = new ChatOpenAI({ model: "gpt-4o", temperature: 0.3 });
//
//   const response = await llm.invoke(
//     `Summarise the following highlighted text in 3 bullet points:
//      "${highlightedText}"
//      Return plain text bullet points only.`
//   );
//   return response.content;
//
// Step 2: In generateFlashcards(), replace the DUMMY block with:
//
//   const response = await llm.invoke(
//     `Create 3 flashcards from this text:
//      "${highlightedText}"
//      Return JSON array: [{ "front": "...", "back": "..." }]`
//   );
//   return JSON.parse(response.content);

import Note from "../models/Note.model.js";
import logger from "../utils/logger.util.js";

/**
 * Generate a summary for a student's highlighted text and save it.
 * @param {{ userId, conceptId, chapterId, highlightedText }} opts
 * @returns {Promise<Note>} saved note document
 */
export async function generateSummary({ userId, conceptId, chapterId, highlightedText }) {
    // ── DUMMY SUMMARY ─────────────────────────────────────────────────────────
    // TO ADD AI: Replace these 3 lines with GPT-4o call (see Step 1 above)
    logger.info("Note summary generated (DUMMY MODE)", { userId, conceptId });
    const summary = `[AI NOTES — DUMMY] Summary of your highlight: "${highlightedText.substring(0, 60)}..."
• Point 1: Key idea from the highlight.
• Point 2: Supporting detail.  
• Point 3: Real-world application.
To get real AI summaries → connect GPT-4o in notes.service.js → generateSummary().`;
    // ─────────────────────────────────────────────────────────────────────────

    const note = await Note.create({
        userId,
        conceptId,
        chapterId,
        highlightedText,
        summary,
        flashcards: [],
    });

    return note;
}

/**
 * Generate flashcards from a chapter or highlight.
 * @param {{ userId, conceptId, highlightedText }} opts
 * @returns {Promise<Array>} array of { front, back }
 */
export async function generateFlashcards({ userId, conceptId, highlightedText }) {
    // ── DUMMY FLASHCARDS ──────────────────────────────────────────────────────
    // TO ADD AI: Replace with GPT-4o call (see Step 2 above)
    logger.info("Flashcards generated (DUMMY MODE)", { userId, conceptId });
    return [
        { front: "[DUMMY] What is this concept about?", back: "It is about the highlighted text (AI will fill this in)." },
        { front: "[DUMMY] Give one example.", back: "Example will be generated by GPT-4o when connected." },
        { front: "[DUMMY] Why is this important?", back: "AI tutor will explain relevance when connected." },
    ];
    // ─────────────────────────────────────────────────────────────────────────
}
